check50:
  files:
    - !exclude "*"
    - !require "programa.cpp"
    - !require "U1rez.txt"

lab50:
  files:
    - !exclude "*"
    - !include "programa.cpp"
    - !include "U1.txt"
    - !include "U1rez.txt"

submit50:
  files:
    - !exclude "*"
    - !include "programa.cpp"
